Repository bZxNetwork/fulcrum_ui, pull requests merged in 2020-04, with the labels that each got.

#143 Fix bug with updating contractsSource
  packages/fulcrum/src/services/FulcrumProvider.ts
Labels: bug

#147 Fulcrum "Insufficient liquidity" message for unlend
  packages/fulcrum/src/components/LendForm.tsx
  packages/fulcrum/src/components/TVChartContainer.tsx
  packages/fulcrum/src/domain/Web3ConnectionFactory.ts
  packages/fulcrum/src/services/FulcrumProvider.ts
  packages/torque/src/assets/artifacts/kovan/iBZx.json
  packages/torque/src/assets/artifacts/rinkeby/iBZx.json
  packages/torque/src/assets/artifacts/ropsten/iBZx.json
  packages/torque/src/domain/Web3ConnectionFactory.ts
Labels: WIP

#157 Add notice for ETH lend popup
  packages/fulcrum/src/components/LendForm.tsx
  packages/fulcrum/src/styles/components/lend-form.mobile.scss
  packages/fulcrum/src/styles/components/lend-form.scss
Labels: LGTM
